export const ADD_USER_DETAILS = "ADD_USER_DETAILS";
export const ADD_USER_TOKEN = "ADD_USER_TOKEN";
export const SUCCESS_ALERT = "SUCCESS_ALERT";
export const FAILURE_ALERT = "FAILURE_ALERT";
export const SHOW_BACKDROP = "SHOW_BACKDROP";
export const HIDE_BACKDROP = "HIDE_BACKDROP";
export const ADD_TEST_DETAILS = "ADD_TEST_DETAILS";
